version: '3'
services:
  web:
    image: nginx:alpine
    container_name: mylaravelapp-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mylaravelapp-app
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres
    container_name: mylaravelapp-db
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:${DB_PORT}"